[package]
name = "decompression"
version = "0.1.0"
edition = "2021"
author = "Sanket Lakhera"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zip = "0.6.2"